Repository kokonior/PHP-Projects, pull requests merged in 2021-10, with the labels that each got.

#1 Update Struktur kendali PHP.php
  Struktur kendali PHP.php
Labels: hacktoberfest-accepted

#2 Update Struktur kendali PHP.php
  Struktur kendali PHP.php
Labels: hacktoberfest-accepted

#3 Update Struktur kendali PHP.php
  Struktur kendali PHP.php
Labels: hacktoberfest-accepted

#4 Update Struktur kendali PHP.php
  Struktur kendali PHP.php
Labels: hacktoberfest-accepted

#5 Update Function.php
  Function.php
Labels: hacktoberfest-accepted

#6 Update Function.php
  Function.php
Labels: hacktoberfest-accepted

#7 Update Function.php
  Function.php
Labels: hacktoberfest-accepted

#9 Update Function.php
  Function.php
Labels: hacktoberfest-accepted

#10 Update Function.php
  Function.php
Labels: hacktoberfest-accepted

#12 Update README.md
  README.md
Labels: hacktoberfest-accepted

#13 Add some codes
  Gunawan ngentoto.php
Labels: hacktoberfest-accepted

#14 Fix some codes
  Gunawan ngentoto.php
Labels: hacktoberfest-accepted

#15 Update Function return.php
  Function return.php
Labels: hacktoberfest-accepted

#16 Add some codes
  Gunawan ngentoto.php
Labels: hacktoberfest-accepted

#17 Update Function return.php
  Function return.php
Labels: hacktoberfest-accepted

#18 Add some codes
  Gunawan ngentoto.php
Labels: hacktoberfest-accepted

#19 Fixed some codes
  Gunawan ngentoto.php
Labels: hacktoberfest-accepted

#20 Update Function return.php
  Function return.php
Labels: hacktoberfest-accepted

#21 Fixed some codes
  Gunawan ngentoto.php
Labels: hacktoberfest-accepted

#22 Update README.md
  README.md
Labels: hacktoberfest-accepted

#23 Update Function return.php
  Function return.php
Labels: hacktoberfest-accepted

#24 Tambahkan
  Gunawan project.php
Labels: hacktoberfest-accepted

#25 Fixed
  Gunawan project.php
Labels: hacktoberfest-accepted

#26 Add code
  Gunawan project.php
Labels: hacktoberfest-accepted

#27 Add codes
  Gunawan project.php
Labels: hacktoberfest-accepted

#28 Fixed code
  Gunawan project.php
Labels: hacktoberfest-accepted

#29 Add codes
  Gunawan project.php
Labels: hacktoberfest-accepted

#30 Fixed codes
  Gunawan project.php
Labels: hacktoberfest-accepted

#31 Function Return
  Function return.php
Labels: hacktoberfest-accepted

#32 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#33 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#34 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#35 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#36 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#37 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#38 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#39 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#40 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#41 Update Array for Users.php
  Array for Users.php
Labels: hacktoberfest-accepted

#43 Update Array for Users.php
  Array for Users.php
Labels: hacktoberfest-accepted

#44 Update README.md
  README.md
Labels: hacktoberfest-accepted

#45 Update Array for Users.php
  Array for Users.php
Labels: hacktoberfest-accepted

#46 Update Array for Users.php
  Array for Users.php
Labels: hacktoberfest-accepted

#47 Update Array for Users.php
  Array for Users.php
Labels: hacktoberfest-accepted

#48 Update Array for Users.php
  Array for Users.php
Labels: hacktoberfest-accepted

#49 Update Array for Users.php
  Array for Users.php
Labels: hacktoberfest-accepted

#50 Update README.md
  README.md
Labels: hacktoberfest-accepted

#51 Update Another Array.php
  Another Array.php
Labels: hacktoberfest-accepted

#53 Update Another Array.php
  Another Array.php
Labels: hacktoberfest-accepted

#54 Update Another Array.php
  Another Array.php
Labels: hacktoberfest-accepted

#55 Update Another Array.php
  Another Array.php
Labels: hacktoberfest-accepted

#56 Update README.md
  README.md
Labels: hacktoberfest-accepted

#57 Update Product.php
  Product.php
Labels: hacktoberfest-accepted

#58 Update Product.php
  Product.php
Labels: hacktoberfest-accepted

#59 Update Product.php
  Product.php
Labels: hacktoberfest-accepted

#60 Update Product.php
  Product.php
Labels: hacktoberfest-accepted

#61 Update Product.php
  Product.php
Labels: hacktoberfest-accepted

#62 Update README.md
  README.md
Labels: hacktoberfest-accepted

#63 Update Product.php
  Product.php
Labels: good first issue, hacktoberfest-accepted

#64 Update Function.php
  Function.php
Labels: hacktoberfest-accepted

#65 Update Function.php
  Function.php
Labels: enhancement, hacktoberfest-accepted

#66 Update Function.php
  Function.php
Labels: enhancement, hacktoberfest-accepted

#67 Update Function.php
  Function.php
Labels: hacktoberfest-accepted

#68 Update Array.php
  Array.php
Labels: good first issue, hacktoberfest-accepted

#69 Update Array.php
  Array.php
Labels: enhancement, hacktoberfest-accepted

#70 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#71 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#72 Update Array.php
  Array.php
Labels: enhancement, hacktoberfest-accepted

#73 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#74 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#75 Update Array.php
  Array.php
Labels: hacktoberfest-accepted

#76 Update README.md
  README.md
Labels: hacktoberfest-accepted

#77 Update Gunawan project.php
  Gunawan project.php
Labels: hacktoberfest-accepted

#78 Update Nanz Nugraha.php
  Nanz Nugraha.php
Labels: hacktoberfest-accepted

#80 Update Gunawan ngentoto.php
  Gunawan ngentoto.php
Labels: hacktoberfest-accepted

#81 Update Nanz Nugraha.php
  Nanz Nugraha.php
Labels: hacktoberfest-accepted

#82 add nullsafe operator
  NullsafeOperator.php
Labels: hacktoberfest-accepted

#83 ASSOCIATIVE ARRAY.php
  ASSOCIATIVE ARRAY.php
Labels: hacktoberfest-accepted

#84 Nanz Nugraha.php
  Nanz Nugraha.php
Labels: hacktoberfest-accepted

#85 Create Rizal Simbolon.php
  Rizal Simbolon.php
Labels: hacktoberfest-accepted

#86 Create mocfaisal.php
  mocfaisal.php
Labels: hacktoberfest-accepted

#87 Create Find Karakter
  Find Karakter
Labels: hacktoberfest-accepted

#88 adminpage
  maspakih.php
Labels: hacktoberfest-accepted

#89 Create rozaqiw.php
  rozaqiw.php
Labels: good first issue, hacktoberfest-accepted

#90 Update maspakih.php
  maspakih.php
Labels: hacktoberfest-accepted

#91 Create rozaqiwt
  rozaqiwt
Labels: hacktoberfest-accepted

#92 Create generate hash with hmac method.php
  generate hash with hmac method.php
Labels: hacktoberfest-accepted

#95 Create Prevent-SQLI
  Prevent-SQLI
Labels: hacktoberfest-accepted

#94 Create nurfaqiih.php
  nurfaqiih.php
Labels: hacktoberfest-accepted

#93 Update maspakih.php
  maspakih.php
Labels: hacktoberfest-accepted

#99 Create convert numbers to roman numerals.php
  convert numbers to roman numerals.php
Labels: hacktoberfest-accepted

#98 Create aksygkm.php
  aksygkm.php
Labels: hacktoberfest-accepted

#96 ASSOCIATIVE ARRAY.php
  ASSOCIATIVE ARRAY.php
Labels: hacktoberfest-accepted

#97 aranda.php
  aranda.php
Labels: hacktoberfest-accepted

#102 Update Sandi L Putra.php
  Sandi L Putra.php
Labels: hacktoberfest-accepted

#103 Update aksygkm.php
  aksygkm.php
Labels: enhancement, hacktoberfest-accepted

#101 Update nurfaqiih.php
  nurfaqiih.php
Labels: enhancement, hacktoberfest-accepted

#100 Create Caesar-cipher.php
  Caesar-cipher.php
Labels: good first issue, hacktoberfest-accepted

#106 Update aksygkm.php
  aksygkm.php
Labels: enhancement, hacktoberfest-accepted

#107 Create hldnkstoumailing.php
  hldnkstoumailing.php
Labels: enhancement, hacktoberfest-accepted

#105 Create rot13.php
  rot13.php
Labels: good first issue, hacktoberfest-accepted

#104 Update nurfaqiih.php
  nurfaqiih.php
Labels: enhancement, hacktoberfest-accepted

#109 Struktur kendali PHP.php
  Struktur kendali PHP.php
Labels: enhancement, hacktoberfest-accepted

#108 Update aksygkm.php
  aksygkm.php
Labels: enhancement, hacktoberfest-accepted

#110 Update nurfaqiih.php
  nurfaqiih.php
Labels: enhancement, hacktoberfest-accepted

#115 struktur kendali.php
  Struktur kendali PHP.php
Labels: hacktoberfest-accepted

#116 Update hldnkstoumailing.php
  hldnkstoumailing.php
Labels: hacktoberfest-accepted

#114 Added How to use cURL to Get JSON Data
  curl_PritamRane.php
Labels: hacktoberfest-accepted

#113 Create shortNumberFormat.php
  shortNumberFormat.php
Labels: good first issue, hacktoberfest-accepted

#112 madefaka2.php
  madefaka2.php
Labels: hacktoberfest-accepted

#111 gojek1.php
  gojek1.php
Labels: hacktoberfest-accepted

#119 ane rifkiw
  ASSOCIATIVE ARRAY.php
Labels: hacktoberfest-accepted

#118 rifkiw.php
  madefaka2.php
Labels: hacktoberfest-accepted

#120 Create enc.php
  enc.php
Labels: Create

#121 Create hldnkstouxssfilter
  hldnkstouxssfilter
Labels: Create

#124 Delete hldnkstouxssfilter
  hldnkstouxssfilter
Labels: hacktoberfest-accepted

#123 Create Hello.php
  Hello.php
Labels: hacktoberfest-accepted, Create

#125 Create hldnkstouxssfilterfunc.php
  hldnkstouxssfilterfunc.php
Labels: hacktoberfest-accepted, Create

#138 Create simple-logout.php
  simple-logout.php
Labels: hacktoberfest-accepted, Create

#137 Create biodata.php
  biodata.php
Labels: hacktoberfest-accepted, Create

#136 Array Sorting In php
  PHP Array Sort.php
Labels: hacktoberfest-accepted

#134 Update ASSOCIATIVE ARRAY.php
  ASSOCIATIVE ARRAY.php
Labels: hacktoberfest-accepted

#133 Create peguranganagus
  peguranganagus
Labels: hacktoberfest-accepted, Create

#132 Create ganjilgenap.php
  ganjilgenap.php
Labels: hacktoberfest-accepted, Create

#131 sironkurus.php
  sironkurus.php
Labels: hacktoberfest-accepted

#130 Zelsaddr patch 1
  zelsaddr.php
Labels: hacktoberfest-accepted

#129 Create bimaexz
  bimaexz.php
Labels: hacktoberfest-accepted, Create

#128 Create kawalcontona.php
  kawalcontona.php
Labels: hacktoberfest-accepted, Create

#127 Create hello_rifqi.php
  hello_rifqi.php
Labels: hacktoberfest-accepted, Create

#140 Create zulnurdiana.php
  zulnurdiana.php
Labels: hacktoberfest-accepted, Create

#141 Update zulnurdiana.php
  zulnurdiana.php
Labels: enhancement, hacktoberfest-accepted

#148 Create Palindrom.php
  Palindrom.php
Labels: hacktoberfest-accepted, Create

#147 Create awsd.php
  awsd.php
Labels: hacktoberfest-accepted, Create

#146 sironkurus.php
  sironkurus.php
Labels: hacktoberfest-accepted

#145 Create efanwahyu.php
  efanwahyu.php
Labels: hacktoberfest-accepted, Create

#144 Create argadw.php
  argadw.php
Labels: hacktoberfest-accepted, Create

#152 Create riodelord-exploit.php
  riodelord-exploit.php
Labels: hacktoberfest-accepted, Create

#151 Create quotesmoment.php
  quotesmoment.php
Labels: hacktoberfest-accepted, Create

#150 Create Format Waktu Indonesia.php
  Format Waktu Indonesia.php
Labels: hacktoberfest-accepted, Create

#149 Create azizrosyid.php
  azizrosyid.php
Labels: hacktoberfest-accepted, Create

#159 sironkurus.php
  sironkurus.php
Labels: good first issue, hacktoberfest-accepted

#158 Update hldnkstoumailing.php
  hldnkstoumailing.php
Labels: good first issue, hacktoberfest-accepted

#157 Update hldnkstouxssfilterfunc.php
  hldnkstouxssfilterfunc.php
Labels: good first issue, hacktoberfest-accepted

#156 Create heading.php
  heading.php
Labels: hacktoberfest-accepted, Create

#155 argadw.php
  argadw
Labels: enhancement, hacktoberfest-accepted

#154 Create random_user.php
  random_user.php
Labels: hacktoberfest-accepted, Create

#153 Create lastofthecode.php
  lastofthecode.php
Labels: hacktoberfest-accepted, Create

#160 create belajarClassDanFunction.php
  belajarClassDanFunction.php
Labels: hacktoberfest-accepted, Create

#163 sironkurus.php
  sironkurus.php
Labels: enhancement, hacktoberfest-accepted

#162 Create oyoAutoRegister.php
  oyoAutoRegister.php
Labels: hacktoberfest-accepted, Create
